import type { Metadata } from 'next'
import '../styles/main426cb2734fc366ca0add.css'
import PagesLayout from '@/components/layouts/PagesLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <PagesLayout>{children}</PagesLayout>
      </body>
    </html>
  )
}
